### ISSUE TITLE
Angular 2 Http Injection in ES5

### ISSUE THREAD

**Issue by developernaren** [jeffbcross/http-design#4]
I just wanted to try out angular2 to learn. I have built a small component but now I am stuck in this part where I need to inject http to make a request to the server for data. I am looking for an example for about 5 hrs and I cannot find one https://angular.io/docs/js/latest/api/http/Http-class.html and this page is stuck in typescript it does not switch back to javascript ( or es5 at least ).
I have searched for last 5 hrs on the internet and found nothing to solve this.

``````
(function(app) {
    app.AppComponent =
        ng.core.Component({
                selector: 'product-detail',
                templateUrl: baseUrl + '/templates/detail.html',
                providers: [ ngHttp.HTTP_PROVIDERS ],
            })
            .Class({
                constructor: [ngHttp.HTTP_PROVIDERS, function( http ) {

                    console.log( http );

                }]
            });
})(window.app || (window.app = {}));``` 

when I use `ngHttp` it just says `ngHttp` is not defined, when I try and include the package `angular/http` using `npm`, it says `system` is not defined, I mean this is just frustrating.

I am not sure if I can post this issue here or not but I am desperate now.
Can you please give me an working example of how to inject this thing, may be starting from which js file to include in html in ES5?
That would be the biggest help.
Thanks.
``````

**Comment by rajeget** [comment]
Hey Naren , you got the ans? 
I am looking for a simple webservice sync app using Angular2 . Its confusing should i use Observables or not ? 

_Raje

**Comment by developernaren** [comment]
@rajegit 
I got this working. this [egg head](https://egghead.io/lessons/angular-2-injecting-a-service)  tutorial helped me a lot, best thing to learn angular 2. been a while not sure what I exactly did, but followed this thing :) hope this helps
